version: '3.8'
services:
  video-merger:
    build: .
    working_dir: /app
    ports:
      - "8086:8000"
    volumes:
      - "/home/caleidro/containers/self-hosted-ai-starter-kit/shared:/data/shared:ro"
      - .:/app
    restart: unless-stopped
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3