services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9020:9090"  # Prometheus web UI
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'  # Retain data for 200 hours (~8 days)
      - '--web.enable-lifecycle'  # Enable hot-reload of configuration
    networks:
      - monitoring
      - tabario

  grafana:
    build: ./grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9010:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password (CHANGE IN PRODUCTION!)
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitoring:
    driver: bridge
  tabario:
    external: true  # Connect to tabario network from main docker-compose.yml
